### ISSUE TITLE
Smoothing function?

### ISSUE THREAD

**Issue by martinaryee** [areyesq89/GenomeMatrix#2]
What function(s) do you recommend for smoothing the matrix (using the `smoothFilt` option)?

**Comment by areyesq89** [comment]
I think I answer privately, but just to close the issue, below is an example on how I used a gaussian smoother (implemented in [`EBImage`](https://www.bioconductor.org/packages/release/bioc/html/EBImage.html)) to smooth a HiC matrix

```
library(HiTC)
library(EBImage)
library(GenomeMatrix)
data(Dixon2012_IMR90, package="HiCDataHumanIMR90")
mat <- as.matrix( hic_imr90_40@.Data[[1]]@intdata )
granges <- hic_imr90_40@.Data[[1]]@xgi
w = makeBrush(size = 5, shape = 'gaussian', sigma = 3)
matrixPlotter( 
    log2(mat+1), 
    granges, 
    plotGR=GRanges("chr1", IRanges( 50000000, 60000000 ) ),  
    zlim=5, 
    smoothFilt = function(x){ filter2( x, w ) }  ) 
```
